package net.developz.classroom.backend.iam.infrastructure.persistence.repositories;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import net.developz.classroom.backend.iam.access.infrastructure.persistence.entity.Role;
import net.developz.classroom.backend.iam.access.infrastructure.persistence.repository.RoleRepository;

import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

@DataJpaTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
class RoleRepositoryTest {

    @Autowired
    private RoleRepository roleRepository;

    @Test
    void shouldSaveAndRetrieveRole() {
        // Arrange
        Role role = new Role();
        role.setRoleName("ROLE_MOCK_ADMIN");

        // Act
        Role savedRole = roleRepository.save(role);

        // Assert
        assertThat(savedRole.getId()).isNotNull(); // ULID generated by interceptor/BaseEntity

        Optional<Role> retrievedRole = roleRepository.findById(savedRole.getId());
        assertThat(retrievedRole).isPresent();
        assertThat(retrievedRole.get().getRoleName()).isEqualTo("ROLE_MOCK_ADMIN");
    }
}


